import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
	return (
		<Html lang="en">
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link
				rel="icon"
				type="image/svg+xml"
				href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22256%22 height=%22256%22 viewBox=%220 0 100 100%22><rect width=%22100%22 height=%22100%22 rx=%2250%22 fill=%22%23161616%22></rect><path d=%22M47.72 29.42L45.20 37.70Q41.24 36.38 38.48 36.38L38.48 36.38Q34.28 36.38 31.88 39.68Q29.48 42.98 28.46 50.24Q27.44 57.50 29.06 60.44Q30.68 63.38 33.74 63.38Q36.80 63.38 39.08 62.48Q41.36 61.58 42.20 61.34L42.20 61.34L43.76 68.30Q37.16 72.26 31.16 72.26L31.16 72.26Q13.88 72.26 16.88 50.54L16.88 50.54Q19.88 27.74 38.12 27.74L38.12 27.74Q43.28 27.74 47.72 29.42L47.72 29.42ZM83.12 29.42L80.60 37.70Q76.64 36.38 73.88 36.38L73.88 36.38Q69.68 36.38 67.28 39.68Q64.88 42.98 63.86 50.24Q62.84 57.50 64.46 60.44Q66.08 63.38 69.14 63.38Q72.20 63.38 74.48 62.48Q76.76 61.58 77.60 61.34L77.60 61.34L79.16 68.30Q72.56 72.26 66.56 72.26L66.56 72.26Q49.28 72.26 52.28 50.54L52.28 50.54Q55.28 27.74 73.52 27.74L73.52 27.74Q78.68 27.74 83.12 29.42L83.12 29.42Z%22 fill=%22%23fff%22></path></svg>"
			/>
			<link
				href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
				rel="stylesheet"
				integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
				crossOrigin="anonymous"></link>
			<script
				src="https://kit.fontawesome.com/abe365b9ec.js"
				async
				crossOrigin="anonymous"></script>
			<Head />
			<body>
				<Main />
				<NextScript />
			</body>
		</Html>
	);
}
