import Head from "next/head";

// importing components from component folder
import Navbar from "@/components/Navbar/Navbar";
import Contact from "@/components/Contact/Contact";
export default function Home() {
	return (
		<>
			<Head>
				<title>Contact Cory</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<Navbar />
			<Contact />
		</>
	);
}
